# Generated by Django 4.0.3 on 2023-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job_Seekers',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
