# Generated by Django 4.0.3 on 2023-04-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_appliedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedPost',
        ),
    ]
