# Generated by Django 4.0.3 on 2023-04-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_appliedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField()),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.job_seeker')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.job_post')),
            ],
        ),
    ]
