# Generated by Django 4.0.3 on 2023-04-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_appliedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedpost',
            name='applied_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.job_seeker'),
        ),
    ]
