# Generated by Django 4.0.3 on 2023-04-17 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_appliedpost_applied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedpost',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.job_seeker'),
        ),
    ]
